---
functional:
  - Доступна возможность регистрации на сайте
  - Отображается уведомление для установки расширения в браузер Google Chrome
  - Доступна возможность зарегистрироваться с помощью GitHub
  - Незарегистрированный пользователь может опробовать платформу по кнопке "Try Simple Battle" на главной странице
  - Зарегистрированному пользователю доступен просмотр лобби на вкладки "Lobby"
  - Зарегистрированному пользователю доступен просмотр турниров на вкладке "Tournaments"
  - Зарегистрированному пользователю доступен просмотр завершенных игр на вкладке "Completed games"
  - Зарегистрированному пользователю доступен общий чат
  - Зарегистрированный пользователь может создать игру, нажав кнопку "Create a game" 
  - Зарегистрированному пользователю доступен общий чат
  - Зарегистрированному пользователю доступен просмотр таблицы лидеров
  - Зарегистрированному доступен выбор языка программирования при создании игры

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - При регистрации нового пользователя должна быть реализована валидация поля email
  - При регистрации нового пользователя должна быть реализована валидация поля password
  - Зарегистрированный пользователь не должен иметь доступ к панели администратора сайта  
